fix do-in-docker args
ddterm/gnome-shell-extension-ddterm pull request #498
Opened 2023-07-22 16:09 UTC by Zerocool56

Add :z flag to volumes. It's fix permission problems on hosts with SELinux (like Fedora 38)
Add HOME env. It's fix permission problems with creation ~/.npm dir

2023-07-23 03:35 UTC, amezin commented
So it happens only with `do-in-docker.sh` because CI runs everything as root, and podman maps host uid to container's root.
But `do-in-docker.sh` keeps host uid which has no corresponding user in the container (no home, no passwd entry, etc).

Storing `HOME` content directly in the working directory doesn't seem like a good idea - at least because that content won't be ignored by git, eslint, etc.

Unless there's a specific reason to keep the content between do-in-docker.sh invocations, I'd prefer `HOME` to be a temporary directory (it will match `do-in-podman.sh` behavior). Otherwise, it should be all kept in a subdirectory (for example, `${SCRIPT_DIR}/.container-home`), and that directory should be added to `.gitignore`. In this case, `do-in-podman.sh` should also be modified accordingly.

Also, could you explain SELinux issue in more detail?

2023-07-25 23:38 UTC, Zerocool56 commented
About selinux
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
As said in official docs, if we mount dir into the container, we should use z option to update selinux labels for correct permissions.
On my fedora38 without this flag i've got a permission error on npm install step.

2023-07-27 11:37 UTC, amezin commented
I don't like the idea of changing permissions (or other attributes) of the files. At least when it could be avoided.

With podman, `--security-opt label=disable` works without `:z`. Since it's not some public production service accessed from an untrusted network, I think `--security-opt label=disable` should be fine.

I can't reproduce the issue with Docker though. Installed as in https://developer.fedoraproject.org/tools/docker/docker-installation.html Have you enabled SELinux support in Docker manually?

2023-07-27 11:41 UTC, amezin requested changes

2023-07-27 11:41 UTC, amezin commented on do-in-docker.sh
> +exec "${docker_cmd[@]}" run --init --rm -i $TTY_FLAG -u $UID_GID -e HOME=${HOME_DIR} -v "${SCRIPT_DIR}:${SCRIPT_DIR}:z" -w "${PWD}" "${IMAGE}:${IMAGE_VERSION}" xvfb-run "$@"
Please add quotes around `HOME=${HOME_DIR}`. It could contain spaces.

2023-07-27 11:41 UTC, amezin commented on do-in-podman.sh
> +exec podman run --init --rm -i $TTY_FLAG -e HOME=${HOME_DIR} -v "${SCRIPT_DIR}:${SCRIPT_DIR}:z" -w "${PWD}" "${IMAGE}:${IMAGE_VERSION}" xvfb-run "$@"
Please add quotes around `HOME=${HOME_DIR}`. It could contain spaces.

Instead of relabeling, please do `--security-opt label=disable`.

2023-07-27 12:21 UTC, Zerocool56 commented
I just install docker from the base repos of Fedora, simply run `dnf install docker` but I suppose it's not necessary.
And SELinux was enabled by default.

About security opt, maybe it's more secure way and we can use it in both situations

2023-07-27 12:44 UTC, amezin commented
> About security opt, maybe it's more secure way

It's "less secure", effectively disabling SELinux. Not disabling completely, just not limiting permissions additionally.

2023-07-27 12:46 UTC, merged

2023-07-27 12:51 UTC, Zerocool56 commented
I meant more secure than relabeling dirs and files.